# Generated by Django 4.0.2 on 2022-03-28 00:31

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1)),
                ('status_type', models.CharField(default='submit', max_length=50)),
                ('class_name', models.CharField(default='danger', max_length=50)),
                ('user_button', models.CharField(default='button', max_length=50)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fundi/images/jobs')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('technician', models.CharField(default='None', max_length=50)),
                ('serial', models.CharField(default='Serial1234', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('serial', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('location', models.CharField(default='Doe', max_length=250)),
                ('tech', models.CharField(default='Jane', max_length=50)),
                ('status', models.CharField(default='accepted', max_length=50)),
                ('serial', models.CharField(default='Serial1234', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('idno', models.IntegerField()),
                ('age', models.IntegerField(default=18)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fundi/images/technician')),
                ('address', models.CharField(default='kitui', max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='fundi/images/customer')),
                ('address', models.CharField(default='John', max_length=50)),
                ('other1', models.CharField(default='Doe', max_length=50)),
                ('other2', models.CharField(default='Jane', max_length=50)),
                ('other3', models.CharField(default='phil', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
